// <auto-generated />
namespace Loadability.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class truck_identifier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(truck_identifier));
        
        string IMigrationMetadata.Id
        {
            get { return "202203171157427_truck_identifier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
