// <auto-generated />
namespace Loadability.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Priority_cfaId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Priority_cfaId));
        
        string IMigrationMetadata.Id
        {
            get { return "202203091154211_Priority_cfaId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
