// <auto-generated />
namespace Loadability.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IS_Compared : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IS_Compared));
        
        string IMigrationMetadata.Id
        {
            get { return "202203211126428_IS_Compared"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
